export default [
    {
        id: 1,
        img: 'healthy-chicken-hell',
        name: 'Chicken Hell',
        highlight: 'healthy',
        time: '24',
        rating: '4.8',
        price: '12.99',
    },
    {
        id: 2,
        img: 'trending-swe-dish',
        name: 'Swe Dish',
        highlight: 'trending',
        time: '34',
        rating: '4.9',
        price: '19.99',
    },
    {
        id: 3,
        img: 'supreme-swe-dish',
        name: 'Fish Hell Veg',
        highlight: 'supreme',
        time: '34',
        rating: '4.9',
        price: '19.99',
    },
    {
        id: 4,
        img: 'healthy-chicken-hell',
        name: 'Chicken Hell',
        highlight: 'healthy',
        time: '24',
        rating: '4.8',
        price: '12.99',
    },
    {
        id: 5,
        img: 'trending-swe-dish',
        name: 'Swe Dish',
        highlight: 'trending',
        time: '34',
        rating: '4.9',
        price: '19.99',
    },
]